services:
  disgo:
    build:
      context: ./discord-bot
      dockerfile: deployments/docker/Dockerfile
    restart: always
    volumes:
      - ~/.config/gcloud:/root/.config/gcloud:ro
    environment:
      # - GOOGLE_APPLICATION_CREDENTIALS=/root/.config/gcloud/application_default_credentials.json NOTE: This is just for me to use :P
      - TZ=America/Los_Angeles